# Generated by Django 4.0.1 on 2022-02-19 16:00

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название языка')),
                ('photo_language', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Язык программирования',
                'verbose_name_plural': 'Языки программирования',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('age', models.SmallIntegerField(verbose_name='Возраст')),
                ('city', models.CharField(max_length=100, verbose_name='Место проживания')),
                ('position', models.CharField(max_length=200, verbose_name='Желаемая должность ')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook-сылка')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Телеграм')),
                ('phone_number', models.CharField(blank=True, max_length=200, verbose_name='Телефон')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Биография опыт работы и.т.д')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('view', models.PositiveIntegerField(default=0)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mysite.language', verbose_name='Основной язык программирования')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
                'ordering': ['-time_update', 'name'],
            },
        ),
    ]
